# Generated by Django 5.0.6 on 2024-05-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prix',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
