# Generated by Django 5.0.6 on 2024-05-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_image_filename_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=0, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
