# Generated by Django 5.0.6 on 2024-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_product_image_remove_product_image_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prix',
            field=models.IntegerField(),
        ),
    ]
