# Generated by Django 5.0.6 on 2024-05-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_warehouse_latitude_remove_warehouse_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(upload_to='main/'),
        ),
    ]
