# Generated by Django 5.0.6 on 2024-06-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_url', models.URLField()),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
