# Generated by Django 5.0.6 on 2024-06-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_partnerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
