# Generated by Django 5.0.6 on 2024-06-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_warehouse_name_alter_warehouse_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartnerLocation',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='category',
            field=models.CharField(choices=[('warehouse', 'Entrepôt'), ('supermarket', 'Supermarché'), ('shopping_center', 'Centre commercial')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
